### DISCUSSION TITLE
Did anyone manage to get scripted and watcher run on a separate IOT network in docker compose?

### DISCUSSION THREAD

**Discussion by johnvpr** [koush/scrypted#1429] [General]
I am trying this but its not working.  and will like to use the same ip for scripted and watcher:

```
version: "3.5"


services:
    scrypted:
        dns:
          - 192.168.20.1

        networks: 
          ipvlan20:
            ipv4_address: 192.168.20.5
        
        environment:

        security_opt:
            - apparmor:unconfined
        volumes:
            - /home/scrypted/volume:/server/volume
        devices: [
         
        ]

        container_name: scrypted
        restart: unless-stopped
  #      network_mode: host
        image: ghcr.io/koush/scrypted


        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "10"
        labels:
            - "com.centurylinklabs.watchtower.scope=scrypted"

    # watchtower manages updates for Scrypted.
    watchtower:
        dns:
          - 192.168.20.1
        networks: 
          ipvlan20:
            ipv4_address: 192.168.20.5
        
        
        environment:
            - WATCHTOWER_HTTP_API_TOKEN=XXXXXX
            - WATCHTOWER_HTTP_API_UPDATE=true
            - WATCHTOWER_SCOPE=scrypted
            # remove the following line to never allow docker to auto update.
            # this is not recommended.
            - WATCHTOWER_HTTP_API_PERIODIC_POLLS=true
        image: containrrr/watchtower
        container_name: scrypted-watchtower
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        labels:
            - "com.centurylinklabs.watchtower.scope=scrypted"
        ports:
            - 10444:8080
        command: --interval 3600 --cleanup --scope scrypted



networks:
  ipvlan20:
    external: true        
```
