### DISCUSSION TITLE
LXC on Proxmox, Core i3 N305, Edge TPU - but no object detection

### DISCUSSION THREAD

**Discussion by degudejung** [koush/scrypted#1459] [Q&A] [answered]
Hi,
I run Scrypted NVR with a subscription for 5 cameras on the following setup
- Intel Core i3 N305
- Coral Edge TPU (M.2 PCIe)
- the "official" LXC container installed via the script on Proxmox 8.2, 8 GB, unprivileged 
- Intel UHD iGPU and Coral Edge TPU passed through / allowed for the LXC (see below)
- 4 cameras connected successfully via ONVIF, 1 via RTSP

Integration of the cameras worked flawlessly. Recordings in NVR are OK. When I open the plugins in the management console, both tensor-flow-lite and open-vino and manually paste snapshots from the cameras, it does detect cars, potted plants, person etc. **However, whatever I chose for object detection, there are "no events in the past 24 hours".** 

Here's how devices look from inside the LXC:
```
ls -l /dev/apex*  
crw-rw-rw- 1 nobody nogroup 120, 0 Apr 28 18:49 /dev/apex_0  
---------- 1 root   root         0 Apr 29 15:37 /dev/apex_1
ls -l /dev/dri/ 
drwxr-xr-x 2 nobody nogroup       80 Apr 28 18:49 by-path
crw-rw-rw- 1 nobody nogroup 226,   0 Apr 28 18:49 card0
crw-rw-rw- 1 nobody nogroup 226, 128 Apr 28 18:49 renderD128
```
...so it looks to me as if the Coral TPU is correctly installed and drivers loaded on the host and that the iGPU is correctly made accessible to the LXC. 

Open-vino shows in the console:
```
Available devices:
CPU :
        SUPPORTED_PROPERTIES:
                AVAILABLE_DEVICES: 
                RANGE_FOR_ASYNC_INFER_REQUESTS: 1, 1, 1
                RANGE_FOR_STREAMS: 1, 4
                EXECUTION_DEVICES: CPU
                FULL_DEVICE_NAME: Intel(R) Core(TM) i3-N305
                OPTIMIZATION_CAPABILITIES: FP32, FP16, INT8, BIN, EXPORT_IMPORT
                DEVICE_TYPE: Type.INTEGRATED
                DEVICE_ARCHITECTURE: intel64
                NUM_STREAMS: 1
                AFFINITY: Affinity.CORE
                INFERENCE_NUM_THREADS: 0
                PERF_COUNT: False
                INFERENCE_PRECISION_HINT: <Type: 'float32'>
                PERFORMANCE_HINT: PerformanceMode.LATENCY
                EXECUTION_MODE_HINT: ExecutionMode.PERFORMANCE
                PERFORMANCE_HINT_NUM_REQUESTS: 0
                ENABLE_CPU_PINNING: True
                SCHEDULING_CORE_TYPE: SchedulingCoreType.ANY_CORE
                ENABLE_HYPER_THREADING: True
                DEVICE_ID: 
                CPU_DENORMALS_OPTIMIZATION: False
                LOG_LEVEL: Level.NO
                CPU_SPARSE_WEIGHTS_DECOMPRESSION_RATE: 1.0
                DYNAMIC_QUANTIZATION_GROUP_SIZE: 0
                KV_CACHE_PRECISION: <Type: 'float16'>

available devices: ['CPU']
model/mode/precision: scrypted_yolov8n_320/AUTO/FP32
/root/.scrypted/volume/plugins/@scrypted/openvino/files/v5/scrypted_yolov8n_320/FP32/best.xml /root/.scrypted/volume/plugins/@scrypted/openvino/files/v5/scrypted_yolov8n_320/FP32/best.bin /root/.scrypted/volume/plugins/@scrypted/openvino/files/scrypted_labels.txt
EXECUTION_DEVICES ['CPU']
/root/.scrypted/volume/plugins/@scrypted/openvino/files/v5/scrypted_yolov9c_flt/FP32/best.xml /root/.scrypted/volume/plugins/@scrypted/openvino/files/v5/scrypted_yolov9c_flt/FP32/best.bin
/root/.scrypted/volume/plugins/@scrypted/openvino/files/v5/vgg_english_g2/FP32/best.xml /root/.scrypted/volume/plugins/@scrypted/openvino/files/v5/vgg_english_g2/FP32/best.bin
/root/.scrypted/volume/plugins/@scrypted/openvino/files/v5/inception_resnet_v1/FP32/best.xml /root/.scrypted/volume/plugins/@scrypted/openvino/files/v5/inception_resnet_v1/FP32/best.bin
/root/.scrypted/volume/plugins/@scrypted/openvino/files/v5/craft/FP32/best.xml /root/.scrypted/volume/plugins/@scrypted/openvino/files/v5/craft/FP32/best.bin
/root/.scrypted/volume/plugins/@scrypted/openvino/files/v5/vgg_english_g2/FP32/best.xml /root/.scrypted/volume/plugins/@scrypted/openvino/files/v5/vgg_english_g2/FP32/best.bin
```
...and under Settings-> Available Devices there is also only"CPU". Should there not also be the iGPU?

In Tensorflow-lite console it shows:
```
coral edge tpu library loaded successfully
edge tpus [{'type': 'pci', 'path': '/dev/apex_0'}]
model: efficientdet_lite0_320_ptq
added tpu {'type': 'pci', 'path': '/dev/apex_0'}
/root/.scrypted/volume/plugins/@scrypted/tensorflow-lite/files/v13/efficientdet_lite0_320_ptq_edgetpu.tflite /root/.scrypted/volume/plugins/@scrypted/tensorflow-lite/files/v13/coco_labels.txt
```

..and under Settings it says "Detected Edge TPU [{"type": "pci", "path": "/dev/apex_0"}]". Model is set to "default"

I am not a Linux pro but so far all this looks pretty OK to me. 

BUT :-(

Whatever I pick on the cameras "Object Detection"->"Advanced" ribbon, be it default, tensorflow-lite or open-vino, I NEVER get any events in the camera stream inside the NVR. I can easily browse through the last hours and see objects appear in great detail but there is no single detection. I even brought the threshold down to 0.3 and tried all three "Decoder" options default, WebAssembly and FFmpeg. I have the same (lack of) effect on the ONVIF and RTSP camera(s).

Please support regarding
1 Should I opt for the Coral TPU or the Intel iGPU (Scrypted NVR is the only reason I bought the Coral TPU)?
2 What am I missing to get things going with object detection? How to start troubleshooting?

Thank you in advance
