### DISCUSSION TITLE
Health check endpoint

### DISCUSSION THREAD

**Discussion by chrisbennight** [koush/scrypted#1796] [Q&A]
Is there a preferred api endpoint or some other mechanism to validate that scrypted is up and running?

I'm running via docker, and am just looking to add a healthcheck there to enable some automation around uptime/reliability.  (Not in response to any particular issue, just best practice.)

**Comment by ekalp** [comment]
I'm currently monitoring the login page, as I couldn't find anything else available, and looking on Discord the question has been asked multiple times without an answer.

**Comment by chrisbennight** [comment]
Doh.  It would be great if there was one that properly indicated camera/plugins/etc were operational, but barring that I basically did what @ekalp suggested:

```
healthcheck:
          test: ["CMD", "curl", "-f", "-k", "-L", "http://127.0.0.1:11080/endpoint/@scrypted/core/public/#/"]
          interval: 1m30s
          timeout: 10s
          retries: 3
          start_period: 40s
```
