### ISSUE TITLE
Scrypted CasaOS

### ISSUE THREAD

**Issue by redfer13** [koush/scrypted#1087]
So im running scrypted on casa os and i configured it like so
note: i hit the export button on casa os
```yaml
name: picturesque_davina
services:
  scrypted:
    cpu_shares: 90
    command: []
    container_name: scrypted
    deploy:
      resources:
        limits:
          memory: 3794M
    environment:
      - SCRYPTED_WEBHOOK_UPDATE=http://localhost:10444/v1/update
      - SCRYPTED_WEBHOOK_UPDATE_AUTHORIZATION=Bearer bearer
    image: koush/scrypted
    labels:
      com.centurylinklabs.watchtower.scope: scrypted
      icon: https://www.scrypted.app/images/web_hi_res_512.png
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: 10m
    ports:
      - target: 11080
        published: "11080"
        protocol: tcp
        host_ip: ""
    restart: unless-stopped
    volumes:
      - type: bind
        source: /.scrypted/volume
        target: /server/volume
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
  watchtower:
    cpu_shares: 90
    command:
      - --interval 3600 --cleanup --scope scrypted
    container_name: scrypted-watchtower
    deploy:
      resources:
        limits:
          memory: 3794M
    environment:
      - WATCHTOWER_HTTP_API_PERIODIC_POLLS=true
      - WATCHTOWER_HTTP_API_TOKEN=qwerty
      - WATCHTOWER_HTTP_API_UPDATE=true
      - WATCHTOWER_SCOPE=scrypted
    image: containrrr/watchtower
    labels:
      com.centurylinklabs.watchtower.scope: scrypted
      icon: https://www.scrypted.app/images/web_hi_res_512.png
    ports:
      - target: 8080
        published: "10444"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://www.scrypted.app/images/web_hi_res_512.png
  index: /
  port_map: "11080"
  scheme: http
  store_app_id: picturesque_davina
  title:
    custom: Scrypted

```
and i get this error when i try load the webpage
Not Found (plugin or device "@scrypted/core" not found)
