### ISSUE TITLE
Cannot pull with docker

### ISSUE THREAD

**Issue by arkcolson** [koush/scrypted#1278]
Hi

When I try to pull a new version I get this error:
```
root@homebridge:/docker_scrypted# docker-compose pull
Pulling scrypted   ... 
Pulling watchtower ... 

ERROR: for watchtower  no matching manifest for linux/armv7l in the manifest list entries

ERROR: for scrypted  no matching manifest for linux/armv7l in the manifest list entries
ERROR: no matching manifest for linux/armv7l in the manifest list entries
```

Running this kernel:
```
root@homebridge:/docker_scrypted# uname -a
Linux homebridge 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux

```
My docker-compose file:
```
version: "2.4"

# The Scrypted docker-compose.yml file typically resides at:
# ~/.scrypted/docker-compose.yml
services:
    scrypted:
        platform: linux/armv7
        environment:
            - SCRYPTED_WEBHOOK_UPDATE_AUTHORIZATION=Bearer xxxx
            - SCRYPTED_WEBHOOK_UPDATE=http://localhost:10444/v1/update
        image: koush/scrypted
        container_name: scrypted
        restart: unless-stopped
        network_mode: host

        volumes:
            - ./scrypted/volume:/server/volume
            # modify and add the additional volume for Scrypted NVR
            # - /media/external:/media/external
        # logging is noisy and will unnecessarily wear on flash storage.
        # scrypted has per device in memory logging that is preferred.
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "10"
        labels:
            - "com.centurylinklabs.watchtower.scope=scrypted"

    # watchtower manages updates for Scrypted.
    watchtower:
        platform: linux/armv7
        environment:
            - WATCHTOWER_HTTP_API_TOKEN=xxxx
            - WATCHTOWER_HTTP_API_UPDATE=true
            - WATCHTOWER_SCOPE=scrypted
            # remove the following line to never allow docker to auto update.
            # this is not recommended.
            - WATCHTOWER_HTTP_API_PERIODIC_POLLS=true
        image: containrrr/watchtower
        container_name: scrypted-watchtower
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        labels:
            - "com.centurylinklabs.watchtower.scope=scrypted"
        ports:
            # The auto update port 10444 can be configured
            # Must match the port in the auto update url above.
            - 10444:8080
        # check for updates once an hour (interval is in seconds)
        command: --interval 3600 --cleanup
```

Docker version:
```
root@homebridge:/docker_scrypted# dpkg -l | grep docker
ii  docker-ce                            5:25.0.0-1~raspbian.10~buster            armhf        Docker: the open-source application container engine
ii  docker-ce-cli                        5:25.0.0-1~raspbian.10~buster            armhf        Docker CLI: the open-source application container engine
ii  docker-ce-rootless-extras            5:25.0.0-1~raspbian.10~buster            armhf        Rootless support for Docker.
ii  docker-compose                       1.21.0-3                                 all          Punctual, lightweight development environments using Docker
ii  docker-compose-plugin                2.24.1-1~raspbian.10~buster              armhf        Docker Compose (V2) plugin for the Docker CLI.
```

Any idea why the pull is not working?
