### ISSUE TITLE
IO error - Invalid argument in DB

### ISSUE THREAD

**Issue by electric-m** [koush/scrypted#1431]
Last night, scrypted has gone into boot-loop after working just fine for ages.
When starting up (in docker), the following error ist output:

```
Error: IO error: /server/volume/scrypted.db/000633.ldb: Invalid argument
```
and the container restarts. That has the effect of a boot loop.

**Server (please complete the following information):**
 - Ubuntu VM under proxmox
 - Installation Method: Docker Compose

The Docke Compose file looks like this and has been working just fine as I said. The "sycrypted" volume is located on a NFS share at my Synology:

```yaml
version: "3.5"

# The Scrypted docker-compose.yml file typically resides at:
# ~/.scrypted/docker-compose.yml

# Example volumes SMB (CIFS) and NFS.
# Uncomment only one.

volumes:
  scrypted:
    external: true
    
#     nvr:
#         driver_opts:
#             type: cifs
#             o: username=[username],password=[password],vers=3.0,file_mode=0777,dir_mode=0777 
#             device: //[ip-address]/[path-to-directory]
#     nvr:
#         driver_opts:
#             type: "nfs"
#             o: "addr=[ip-address],nolock,soft,rw"
#             device: ":[path-to-directory]"

services:
    scrypted:
        image: koush/scrypted:latest
        environment:
            - SCRYPTED_WEBHOOK_UPDATE_AUTHORIZATION=Bearer xyckkhsfdgjzghfkjgskndmfghzvdfgz
            - SCRYPTED_WEBHOOK_UPDATE=http://localhost:10444/v1/update
            # nvidia support
            # - NVIDIA_VISIBLE_DEVICES=all
            # - NVIDIA_DRIVER_CAPABILITIES=all
        # runtime: nvidia
        container_name: scrypted
        restart: unless-stopped
        network_mode: host

        # uncomment this and a line below as needed.
        # devices:
        # zwave usb serial device
        #   - /dev/ttyACM0:/dev/ttyACM0
        # all usb devices, such as coral tpu
        #   - /dev/bus/usb:/dev/bus/usb
        # intel hardware accelerated video decoding
        #   - /dev/dri:/dev/dri

        volumes:
            - scrypted:/server/volume
            
            # uncomment the following lines to expose Avahi, an mDNS advertiser.
            # make sure Avahi is running on the host machine, otherwise this will not work.
            # - /var/run/dbus:/var/run/dbus
            # - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
        # logging is noisy and will unnecessarily wear on flash storage.
        # scrypted has per device in memory logging that is preferred.
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "10"
        labels:
            - "com.centurylinklabs.watchtower.scope=scrypted"
```
