### ISSUE TITLE
"Could not reach scrypted home automation"

### ISSUE THREAD

**Issue by gvdhoven** [koush/scrypted#229]
While linking the Google Home app to my scrypted install i get the message: "Could not reach scrypted home automation"

Background:
- Fresh install of Scrypted (Version 0.0.171)
- Running behind Traefik with SSL certificate.
- I have no 'authentication' setup on my reverse proxy, so opening the URL takes me directly to scrypted.
- Cloud and Unifi plugins installed & cloud login done with my Google account
- Accessible via both my hostname and via `scrypted.app` login, but not while opening it from the Google Home App.

Worth mentioning that if i choose a different google account to try and link i get the 'not reigstered' message so i am pretty sure my connection to Scrypted.app is correct. I also had to setup a 'hostname' and that redirects the scrypted.app login to my hostname.

I might be missing some redirects or ports in below config?

This is my docker-compose file:
```
  automation-scrypted:
    image: koush/scrypted
    depends_on:
      - core-traefik-fa
    container_name: automation-scrypted
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
    networks:
      traefik:
    ports:
      - 11080:11080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/docker/automation/scrypted/data:/server/volume
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.automation-scrypted.rule=Host(`my.scrypted.hostname`)"
      - "traefik.http.routers.automation-scrypted.entrypoints=websecure"
      - "traefik.http.routers.automation-scrypted.service=automation-scrypted"
      - "traefik.http.services.automation-scrypted.loadbalancer.server.port=11080"
```

Any clue what i am missing?
