### ISSUE TITLE
Documentation only allows host networking

### ISSUE THREAD

**Issue by agocke** [koush/scrypted#477]
I'd like to give this a try to manage my RTSP cameras, but it only states that it supports host networking and doesn't list which ports it uses.

This is a non-starter for me as I never allow any containers to use host networking because

1. It can and has resulted in port conflicts
2. Doesn't allow me to easily audit what services are publicly accessible
3. Interacts very poorly with mDNS since I have multiple mDNS services running on the same box.

Could documentation be added for avoiding host networking?

**Comment by koush** [comment]
1. rtp through docker's source nat is problematic if the initial hole punch or stun fails.
2. every homekit accessory uses a random (but documented port) tcp listener port.

scrypted itself only really needs 10443. it's the other video streaming services on random ports that is the issue. if you want to deal with `2` above, you could probably get it working. Feel free to create a wiki entry. This is not something I want to encourage because it becomes a support nightmare on the issue tracker. I've tried. Not worth it.

**Comment by agocke** [comment]
> every homekit accessory uses a random (but customizable) tcp listener port.

So does scrypted work by querying via mDNS for the accessories? And the problem is running mDNS through the NAT?

**Comment by koush** [comment]
> > every homekit accessory uses a random (but customizable) tcp listener port.
> 
> So does scrypted work by querying via mDNS for the accessories? And the problem is running mDNS through the NAT?

I'm not sure what exactly you're referring to. I'm going to guess you are talking about Homekit.

Scrypted will advertise homekit accessories (cameras) or bridges (everything else) with mdns. It does not query mdns at all for homekit.

Scrypted does query mdns for other plugins, like chromecast I believe. Maybe google home as well.

**Comment by agocke** [comment]
Sorry for the delay, took me a bit to get back to this.

So, I've think I've successfully got host networking running. The main thing I didn't understand at first is that scrypted doesn't actually act as a full bridge for each of the camera services. Instead, the accessories are each connected to HomeKit directly -- sounds like that's for performance.

Anyway, you're right, that does make things more complicated. In particular, it means that adding a new accessory means resolving a fixed port for that accessory in scrypted, then adding that port to the compose file. Overall, not too big a deal. My compose file ends up looking like this:

```
version: "3.5"

services:
    scrypted:
        environment:
            - SCRYPTED_WEBHOOK_UPDATE_AUTHORIZATION=Bearer <elided>
            - SCRYPTED_WEBHOOK_UPDATE=http://localhost:10444/v1/update
        image: koush/scrypted
        container_name: scrypted
        restart: unless-stopped
          # network_mode: host
        ports:
          - 10443:10443
          - 43929:43929
          - 47649:47649
          - 46523:46523

        # uncomment this and a line below as needed.
        # devices:
        # zwave usb serial device
        #   - /dev/ttyACM0:/dev/ttyACM0
        # all usb devices, such as coral tpu
        #   - /dev/bus/usb:/dev/bus/usb

        volumes:
            - /storage/config/data/scrypted:/server/volume
            # modify and add the additional volume for Scrypted NVR
            # - /media/external:/media/external
        # logging is noisy and will unnecessarily wear on flash storage.
        # scrypted has per device in memory logging that is preferred.
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "10"
        labels:
            - "com.centurylinklabs.watchtower.scope=scrypted"

    # watchtower manages updates for Scrypted.
    watchtower:
        environment:
            - WATCHTOWER_HTTP_API_TOKEN=<elided>
            - WATCHTOWER_HTTP_API_UPDATE=true
            - WATCHTOWER_SCOPE=scrypted
            # remove the following line to never allow docker to auto update.
            # this is not recommended.
            - WATCHTOWER_HTTP_API_PERIODIC_POLLS=true
        image: containrrr/watchtower
        container_name: scrypted-watchtower
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        labels:
            - "com.centurylinklabs.watchtower.scope=scrypted"
        ports:
            # The auto update port 10444 can be configured
            # Must match the port in the auto update url above.
            - 10444:8080
        # check for updates once an hour (interval is in seconds)
        command: --interval 3600 --cleanup
```

The next problem is how to advertise all of the mDNS services so that homekit can find them. In my case what I prefer to do is have a single avahi instance running on the docker host and have services configured for each of the different things running on the host. Since you need an avahi service for each device, I've found that the easiest way to get the service definition is just to dump the services locally on the host, then copy them into a service config.

If you run `avahi-browse --all --terminate --resolve > ~/avahidump.txt` then that should show you all the published services, including the ones on the docker virtual network devices. You can then copy the results from the avahi dump into a service definition for avahi-daemon. For example, the output

```
_hap._tcp            local
   hostname = [19_18_76_e7_6d_ae.local]
   address = [172.27.0.3]
   port = [47649]
   txt = ["sh=ZTy3AA==" "ci=18" "sf=0" "s#=1" "pv=1.1" "md=Doorbell Wired (doorbell_graham_cracker)" 
```

for my door camera ends up looking like

```
<service-group>
  <name>Front Door</name>
  <service>
    <type>_hap._tcp</type>
    <port>47649</port>

    <!-- setup hash (used for pairing).
         Required to support enhanced
         setup payload information (but
         not defined in the spec)        -->
    <txt-record>sh=ZTy3AA==</txt-record>

    <!-- accessory category -->
    <txt-record>ci=18</txt-record>

    <!-- Status flags
         0=not paired, 1=paired -->
    <txt-record>sf=1</txt-record>

    <!-- accessory state
          This must have a value of 1 -->
    <txt-record>s#=1</txt-record>

    <!-- HAP version -->
    <txt-record>pv=1.1</txt-record>

    <!-- friendly name -->
    <txt-record>md=Front Door Cam</txt-record>

    <!-- MAC -->
    <txt-record>id=19:18:76:e7:6d:ae</txt-record>

    <!-- Pairing Feature Flags
         nothing to configure -->
    <txt-record>ff=0</txt-record>

    <!-- Current configuration number -->
    <txt-record>c#=2</txt-record>

  </service>
</service-group>
```

as a service definition inside `/etc/avahi/services/front-door-cam.service`.

After you do all that, things seem to work OK. HomeKit can add the services and things still seem accessible a couple hours later.
