### ISSUE TITLE
Docker - Nvidia GPU Support

### ISSUE THREAD

**Issue by JHeat** [koush/scrypted#485]
Hello,

Are there any plans for [Nvidia Driver support in Docker](https://gitlab.com/nvidia/container-images/cuda/-/blob/master/dist/11.5.0/ubuntu2004/base/Dockerfile)? I run unRAID, where all of my containers have this capability baked in. The reason I ask is the Reolink Trackmix PoE doesn't have a high resolution h264 stream available, h265 however is but I am unable to change the codec properties.

For reference, I currently run [Shinobi w/ Nvidia driver capabilities](https://hub.docker.com/r/spaceinvaderone/shinobi_pro_unraid), which allows me to leverage HWAccel for the H265 Stream.

Side Note: I remember seeing your name in the Cyanogenmod and Android dev, years back. Nice to see you working on yet another stellar project!

**Comment by koush** [comment]
```
version: "3.5"

services:
    scrypted:
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
            - SCRYPTED_WEBHOOK_UPDATE_AUTHORIZATION=abccd
            - SCRYPTED_WEBHOOK_UPDATE=http://localhost:10444/v1/update
        image: koush/scrypted:beta
        container_name: scrypted
        restart: unless-stopped
        runtime: nvidia
        network_mode: host
        volumes:
            - ~/.scrypted/volume:/server/volume
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "10"
        labels:
            - "com.centurylinklabs.watchtower.scope=scrypted"
        devices:
          - /dev/ttyACM0:/dev/ttyACM0
        #   - /dev/bus/usb:/dev/bus/usb

    # watchtower manages updates for Scrypted.
    watchtower:
        environment:
            - WATCHTOWER_HTTP_API_TOKEN=abcd
            - WATCHTOWER_HTTP_API_UPDATE=true
            - WATCHTOWER_SCOPE=scrypted
            # remove the following line to never allow docker to auto update.
            # this is not recommended.
            - WATCHTOWER_HTTP_API_PERIODIC_POLLS=true
        image: containrrr/watchtower
        container_name: scrypted-watchtower
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        labels:
            - "com.centurylinklabs.watchtower.scope=scrypted"
        ports:
            # The auto update port 10444 can be configured
            # Must match the port in the auto update url above.
            - 10444:8080
        # check for updates once an hour (interval is in seconds)
        command: --interval 3600 --cleanup
```

**Comment by koush** [comment]
You will need to mount ffmpeg with nvidia support into container too.

**Comment by JHeat** [comment]
> need Nvidia docker runtime installed.
> 
> 
> 
> ```
> 
> version: "3.5"
> 
> 
> 
> services:
> 
>     scrypted:
> 
>         environment:
> 
>             - NVIDIA_VISIBLE_DEVICES=all
> 
>             - NVIDIA_DRIVER_CAPABILITIES=all
> 
>             - SCRYPTED_WEBHOOK_UPDATE_AUTHORIZATION=abccd
> 
>             - SCRYPTED_WEBHOOK_UPDATE=http://localhost:10444/v1/update
> 
>         image: koush/scrypted:beta
> 
>         container_name: scrypted
> 
>         restart: unless-stopped
> 
>         runtime: nvidia
> 
>         network_mode: host
> 
>         volumes:
> 
>             - ~/.scrypted/volume:/server/volume
> 
>         logging:
> 
>             driver: "json-file"
> 
>             options:
> 
>                 max-size: "10m"
> 
>                 max-file: "10"
> 
>         labels:
> 
>             - "com.centurylinklabs.watchtower.scope=scrypted"
> 
>         devices:
> 
>           - /dev/ttyACM0:/dev/ttyACM0
> 
>         #   - /dev/bus/usb:/dev/bus/usb
> 
> 
> 
>     # watchtower manages updates for Scrypted.
> 
>     watchtower:
> 
>         environment:
> 
>             - WATCHTOWER_HTTP_API_TOKEN=abcd
> 
>             - WATCHTOWER_HTTP_API_UPDATE=true
> 
>             - WATCHTOWER_SCOPE=scrypted
> 
>             # remove the following line to never allow docker to auto update.
> 
>             # this is not recommended.
> 
>             - WATCHTOWER_HTTP_API_PERIODIC_POLLS=true
> 
>         image: containrrr/watchtower
> 
>         container_name: scrypted-watchtower
> 
>         restart: unless-stopped
> 
>         volumes:
> 
>             - /var/run/docker.sock:/var/run/docker.sock
> 
>         labels:
> 
>             - "com.centurylinklabs.watchtower.scope=scrypted"
> 
>         ports:
> 
>             # The auto update port 10444 can be configured
> 
>             # Must match the port in the auto update url above.
> 
>             - 10444:8080
> 
>         # check for updates once an hour (interval is in seconds)
> 
>         command: --interval 3600 --cleanup
> 
> ```

Will try this tonight and report back. Thanks!

**Comment by jonathanjsimon** [comment]
Drudging this up....

I have the latest docker image containing scrypted 0.39.0 with all the appropriate nvidia environment things set, runtime is set to nvidia, etc, `ffmpeg` inside the container reports that `cuda` is available as a hw acceleration method, but `nvidia-smi` does not report any tasks are running on the GPU and the CPU is definitely being consumed. Various nvidia things are listed inside the container at `/dev/`. Is there something I've missed? Thanks!


compose:
```
version: "3.5"
services:
    scrypted:
        image: koush/scrypted
        environment:
            - SCRYPTED_WEBHOOK_UPDATE_AUTHORIZATION=Bearer myspecialdata
            - SCRYPTED_WEBHOOK_UPDATE=http://localhost:10444/v1/update
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
        runtime: nvidia
        container_name: scrypted
        restart: unless-stopped
        network_mode: host
        volumes:
            - /media/storage/docker_configs/scrypted/:/server/volume
            - /media/storage/security_video:/nvr
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "10"
```

ffmpeg:
```
❯ sudo docker exec -it scrypted bash
[sudo] password for [me]: 
root@server:/server# cd
root@server:~# which ffmpeg
/usr/bin/ffmpeg
root@kunlun:~# ffmpeg -hwaccels
ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Hardware acceleration methods:
vdpau
cuda
vaapi
qsv
drm
opencl
```

`/dev` inside container:
```
root@server:/dev# ls -l
total 0
lrwxrwxrwx 1 root root       11 Jun 21 01:34 core -> /proc/kcore
drwxr-xr-x 3 root root      100 Jun 21 01:34 dri
lrwxrwxrwx 1 root root       13 Jun 21 01:34 fd -> /proc/self/fd
crw-rw-rw- 1 root root   1,   7 Jun 21 01:34 full
drwxrwxrwt 2 root root       40 Jun 21 01:34 mqueue
crw-rw-rw- 1 root root   1,   3 Jun 21 01:34 null
crw-rw-rw- 1 root root 195, 254 Jun 21 01:34 nvidia-modeset
crw-rw-rw- 1 root root 237,   0 Jun 21 01:34 nvidia-uvm
crw-rw-rw- 1 root root 237,   1 Jun 21 01:34 nvidia-uvm-tools
crw-rw-rw- 1 root root 195,   0 Jun 21 01:34 nvidia0
crw-rw-rw- 1 root root 195, 255 Jun 21 01:34 nvidiactl
lrwxrwxrwx 1 root root        8 Jun 21 01:34 ptmx -> pts/ptmx
drwxr-xr-x 2 root root        0 Jun 21 01:34 pts
crw-rw-rw- 1 root root   1,   8 Jun 21 01:34 random
drwxrwxrwt 2 root root       40 Jun 21 01:34 shm
lrwxrwxrwx 1 root root       15 Jun 21 01:34 stderr -> /proc/self/fd/2
lrwxrwxrwx 1 root root       15 Jun 21 01:34 stdin -> /proc/self/fd/0
lrwxrwxrwx 1 root root       15 Jun 21 01:34 stdout -> /proc/self/fd/1
crw-rw-rw- 1 root root   5,   0 Jun 21 01:34 tty
crw-rw-rw- 1 root root   1,   9 Jun 21 01:34 urandom
crw-rw-rw- 1 root root   1,   5 Jun 21 01:34 zero
```
