### ISSUE TITLE
Docker-Compose

### ISSUE THREAD

**Issue by nate8199** [koush/scrypted#8]
I made this docker-compose file if you wish to share it in your README, IDK how to pull-request it

edited to add a z-wave USB stick into the container via devices:

```
version: '3.5'

services:
    scrypted:
        image: koush/scrypted
        container_name: scrypted
        restart: unless-stopped
        ports:
            - 9443:9443
        environment:
            - TZ=America/Seattle
        devices:
            - /dev/ttyACM0
        volumes:
            - LOCAL_STORAGE/scrypted:/server/volume

```
