### ISSUE TITLE
Alexa not recognizing Unifi G4 Doorbell Pro as doorbell via Scrypted Alexa plugin

### ISSUE THREAD

**Issue by alams154** [koush/scrypted#903]
Scrypted recognizes the G4 Doorbell Pro as a doorbell within the Scrypted Unifi Protect Plugin:
![image](https://github.com/koush/scrypted/assets/31905246/91c2461a-c9cb-46e8-8443-41b28b184d7e)

but that is not reflected in the Alexa app where it is only recognized as a camera:
![image](https://github.com/koush/scrypted/assets/31905246/f6a1709a-f992-4a38-982d-ec1f3c487fc6)

I'm assuming that it should be detected as a doorbell type based on this script https://github.com/koush/scrypted/blob/main/plugins/alexa/src/types/doorbell.ts

Unifi Setup:
UDM Pro running UniFi OS 3.0.20 and Protect 2.8.28

Scrypted Setup:
Unifi Protect Plugin running 0.0.133
Scypted Cloud running 0.1.14 (with Port Forwarding disabled)
Alexa running 0.2.5

Scrypted is running as a docker container through docker-compose with the following service:
```
scrypted:
        image: koush/scrypted
        container_name: scrypted
        devices:
            - /dev/dri:/dev/dri
        environment:
            - SCRYPTED_WEBHOOK_UPDATE_AUTHORIZATION=Bearer REDACTED
            - SCRYPTED_WEBHOOK_UPDATE=http://localhost:10444/v1/update
        volumes:
            - ./scrypted_data:/server/volume
        network_mode: host
        restart: unless-stopped
```

I am able to see the live view for all the Unifi cameras (including the doorbell) from within the Alexa app.

Should the G4 be detected as a doorbell in the Alexa app?  I'm not sure what logs would help or what would be the best way to collect logs that might help debug this but please let me know if you need any additional information.

The main feature I am after is having the doorbell view show up on my Echo Show devices after the doorbell is pressed which I am hoping is possible if the G4 is detected as a doorbell.

Thanks for any help on this and the hard work on Scrypted!
